use_frameworks!

platform :ios, '10.0'

target 'MKLoRaDeviceModePageModule_Example' do
  pod 'MKLoRaDeviceModePageModule', :path => '../'

  target 'MKLoRaDeviceModePageModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
